// GENERATED by @edgedb/generate v0.5.3

import type {Executor} from "edgedb";


export type GetMovieReturns = {
  "title": string;
  "actors": Array<{
    "name": string;
  }>;
} | null;

export function getMovie(client: Executor): Promise<GetMovieReturns> {
  return client.querySingle(`\
select Movie {
      title,
      actors: {
        name,
      }
    } filter .title = "Iron Man 2"`);

}
